import type { VoiceStyle } from './types.ts';

export const SUPERTONIC_HF_BASE = 'https://huggingface.co/Supertone/supertonic-3/resolve/main';

export const MODEL_FILES = {
	durationPredictor: `${SUPERTONIC_HF_BASE}/onnx/duration_predictor.onnx`,
	textEncoder: `${SUPERTONIC_HF_BASE}/onnx/text_encoder.onnx`,
	vectorEstimator: `${SUPERTONIC_HF_BASE}/onnx/vector_estimator.onnx`,
	vocoder: `${SUPERTONIC_HF_BASE}/onnx/vocoder.onnx`,
	unicodeIndexer: `${SUPERTONIC_HF_BASE}/onnx/unicode_indexer.json`,
	ttsJson: `${SUPERTONIC_HF_BASE}/onnx/tts.json`,
};

export const VOICE_STYLES: VoiceStyle[] = [
	{ id: 'M1', name: 'Nam 1 (Trầm)', path: 'assets/voice_styles/M1.json', gender: 'male' },
	{ id: 'M2', name: 'Nam 2 (Ấm)', path: 'assets/voice_styles/M2.json', gender: 'male' },
	{ id: 'M3', name: 'Nam 3 (Hùng)', path: 'assets/voice_styles/M3.json', gender: 'male' },
	{ id: 'M4', name: 'Nam 4 (Trẻ)', path: 'assets/voice_styles/M4.json', gender: 'male' },
	{ id: 'M5', name: 'Nam 5 (Dịu)', path: 'assets/voice_styles/M5.json', gender: 'male' },
	{ id: 'F1', name: 'Nữ 1 (Nhẹ)', path: 'assets/voice_styles/F1.json', gender: 'female' },
	{ id: 'F2', name: 'Nữ 2 (Trong)', path: 'assets/voice_styles/F2.json', gender: 'female' },
	{ id: 'F3', name: 'Nữ 3 (Cao)', path: 'assets/voice_styles/F3.json', gender: 'female' },
	{ id: 'F4', name: 'Nữ 4 (Mềm)', path: 'assets/voice_styles/F4.json', gender: 'female' },
	{ id: 'F5', name: 'Nữ 5 (Vang)', path: 'assets/voice_styles/F5.json', gender: 'female' },
];

export const STORAGE_KEYS = {
	ACTIVE_VOICE: 'readit_active_voice',
	SPEED: 'readit_speed',
	READ_MODE_SETTINGS: 'readit_read_mode_settings',
	PLAYBACK_SESSION: 'readit_playback_session',
	THEME: 'readit_active_theme',
	SELECTION_BUTTON_ENABLED: 'readit_selection_button_enabled',
	WORD_HIGHLIGHT_ENABLED: 'readit_word_highlight_enabled',
};

export const PRIVACY_POLICY_URL = 'https://tunglt1810.github.io/readit.dev/privacy-policy/';

export const BUY_ME_A_COFFEE_URL = 'https://buymeacoffee.com/bbeeezzzzz';

export const THEME_TRANSLATIONS = {
	vi: {
		selectTheme: 'Chọn giao diện',
		themeDefault: '📱 Hiện đại',
		themeWinamp: '🕹️ Classic (1998)',
		themeWmp12: '💿 Vista Aero (2006)',
		themeDefaultName: 'Hiện đại',
		themeWinampName: 'Classic (1998)',
		themeWmp12Name: 'Vista Aero (2006)',
		winampTitle: 'WINAMP CỔ ĐIỂN',
		voiceConfig: 'CẤU HÌNH GIỌNG ĐỌC',
		readCurrentPage: 'Đọc trang này thay thế',
		readPage: 'Đọc trang hiện tại',
		stopReading: 'Dừng đọc bài',
		nowPlaying: 'Đang phát',
		playingStatus: 'Đang đọc đoạn',
		readyStatus: 'Sẵn sàng đọc trang web',
		preparingState: 'Đang chuẩn bị giọng đọc...',
		pauseState: 'Tạm dừng',
		errorState: 'Lỗi hoạt động',
		resumeStatus: 'Tiếp tục',
		selectVoice: 'Chọn giọng (Supertonic 3)',
		readingSpeed: 'Tốc độ đọc',
		loadingModel: 'Đang tải model',
		modelLoadFailed: 'Không thể tải model',
		unknownError: 'Lỗi không xác định',
		startReadingFailed: 'Không thể bắt đầu đọc trang này. Vui lòng thử lại.',
		openSidePanel: 'Mở Side Panel',
		openSidePanelFailed: 'Không thể mở Side Panel. Vui lòng thử lại.',
		currentPage: 'Trang hiện tại',
		orPasteText: 'Hoặc dán văn bản',
		pasteTextPlaceholder: 'Dán hoặc nhập nội dung cần đọc',
		readPastedText: 'Đọc văn bản đã dán',
		clearText: 'Xóa',
		characters: 'ký tự',
		manualLanguage: 'Ngôn ngữ văn bản',
		languageAuto: 'Tự động',
		languageEnglish: 'English',
		languageVietnamese: 'Tiếng Việt',
		languageChinese: '中文',
		textProcessedLocally: 'Nội dung chỉ được xử lý trên thiết bị.',
		currentPageUnavailable: 'Không thể đọc trang hiện tại',
		invalidManualText: 'Hãy nhập văn bản cần đọc.',
		manualReaderLabel: 'Văn bản đang đọc',
		manualPausedForWeb: 'Đọc trong editor đã tạm dừng để đọc web.',
		resumeEditorReading: 'Tiếp tục đọc trong editor',
		stopEditorReading: 'Dừng đọc trong editor',
		manualCheckpointUnavailable: 'Phiên đọc trong editor không còn khả dụng. Hãy bắt đầu lại.',
		manualCheckpointFailed: 'Không thể tạm dừng đọc trong editor. Chưa bắt đầu đọc web.',
		paragraphLabel: 'Đoạn',
		preparingContent: 'Đang chuẩn bị nội dung',
		readingOtherTab: 'Đang đọc ở tab khác',
		readingThisTab: 'Đang đọc ở tab này',
		pastedText: 'Văn bản đã dán',
		manualSession: 'Phiên đọc văn bản',
		privacyDisclosure: 'Nội dung được xử lý trên thiết bị, không gửi lên server.',
		learnMore: 'Tìm hiểu thêm',
		buyMeCoffee: 'Ủng hộ tôi một ly cà phê',
		feedback: 'Phản hồi',
		privacyPolicy: 'Chính sách quyền riêng tư',
		showSelectionButton: 'Hiện nút đọc cạnh văn bản đã chọn',
		readSelectedText: 'Đọc văn bản đã chọn',
		showWordHighlight: 'Tô sáng từ đang đọc trên trang',
	},
	en: {
		selectTheme: 'Select Theme',
		themeDefault: '📱 Modern',
		themeWinamp: '🕹️ Classic (1998)',
		themeWmp12: '💿 Vista Aero (2006)',
		themeDefaultName: 'Modern',
		themeWinampName: 'Classic (1998)',
		themeWmp12Name: 'Vista Aero (2006)',
		winampTitle: 'WINAMP CLASSIC',
		voiceConfig: 'VOICE CONFIGURATION',
		readCurrentPage: 'Read this page instead',
		readPage: 'Read current page',
		stopReading: 'Stop reading',
		nowPlaying: 'Now Playing',
		playingStatus: 'Reading paragraph',
		readyStatus: 'Ready to read page',
		preparingState: 'Preparing voice...',
		pauseState: 'Paused',
		errorState: 'Playback Error',
		resumeStatus: 'Resume',
		selectVoice: 'Select Voice (Supertonic 3)',
		readingSpeed: 'Reading Speed',
		loadingModel: 'Loading model',
		modelLoadFailed: 'Unable to load model',
		unknownError: 'Unknown error',
		startReadingFailed: 'Unable to start reading this page. Please try again.',
		openSidePanel: 'Open Side Panel',
		openSidePanelFailed: 'Unable to open the Side Panel. Please try again.',
		currentPage: 'Current page',
		orPasteText: 'Or paste text',
		pasteTextPlaceholder: 'Paste or type text to read',
		readPastedText: 'Read pasted text',
		clearText: 'Clear',
		characters: 'characters',
		manualLanguage: 'Text language',
		languageAuto: 'Auto',
		languageEnglish: 'English',
		languageVietnamese: 'Vietnamese',
		languageChinese: 'Chinese',
		textProcessedLocally: 'Text is processed only on this device.',
		currentPageUnavailable: 'Current page unavailable',
		invalidManualText: 'Enter text to read.',
		manualReaderLabel: 'Text being read',
		manualPausedForWeb: 'Editor reading is paused while web reading plays.',
		resumeEditorReading: 'Resume editor reading',
		stopEditorReading: 'Stop editor reading',
		manualCheckpointUnavailable: 'Editor reading is no longer available. Start it again.',
		manualCheckpointFailed: 'Unable to pause editor reading. Web reading was not started.',
		paragraphLabel: 'Paragraph',
		preparingContent: 'Preparing content',
		readingOtherTab: 'Reading in another tab',
		readingThisTab: 'Reading in this tab',
		pastedText: 'Pasted text',
		manualSession: 'Manual text session',
		privacyDisclosure: 'Content is processed on your device and is not sent to a server.',
		learnMore: 'Learn more',
		buyMeCoffee: 'Buy me a coffee',
		feedback: 'Feedback',
		privacyPolicy: 'Privacy Policy',
		showSelectionButton: 'Show read button for selected text',
		readSelectedText: 'Read selected text',
		showWordHighlight: 'Highlight the word being read on the page',
	},
} as const;

export const VOICE_STYLE_TRANSLATIONS = {
	vi: {
		M1: 'Nam 1 (Trầm)',
		M2: 'Nam 2 (Ấm)',
		M3: 'Nam 3 (Hùng)',
		M4: 'Nam 4 (Trẻ)',
		M5: 'Nam 5 (Dịu)',
		F1: 'Nữ 1 (Nhẹ)',
		F2: 'Nữ 2 (Trong)',
		F3: 'Nữ 3 (Cao)',
		F4: 'Nữ 4 (Mềm)',
		F5: 'Nữ 5 (Vang)',
	},
	en: {
		M1: 'Male 1 (Deep)',
		M2: 'Male 2 (Warm)',
		M3: 'Male 3 (Strong)',
		M4: 'Male 4 (Young)',
		M5: 'Male 5 (Gentle)',
		F1: 'Female 1 (Light)',
		F2: 'Female 2 (Clear)',
		F3: 'Female 3 (High)',
		F4: 'Female 4 (Soft)',
		F5: 'Female 5 (Resonant)',
	},
} as const;
