import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { createCrfDetector, decodePortableCrfModel, reconstructDetectedSpans } from '../../src/offscreen/vietnamese/crf.ts';
import { tokenizeVietnameseText } from '../../src/offscreen/vietnamese/tokenizer.ts';
import type { CheckpointLabel, SourceToken } from '../../src/offscreen/vietnamese/types.ts';

const assetRoot = new URL('../../public/assets/vietnamese-normalizer/', import.meta.url);

function readAsset(name: string): Buffer {
	return readFileSync(new URL(name, assetRoot));
}

function exactArrayBuffer(buffer: Buffer): ArrayBuffer {
	return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer;
}

function encodeModel(options: { padding?: number; transitionWeight?: number } = {}): ArrayBuffer {
	const attributes = ['wi:11', 'wi:07'];
	const states = [
		[0, 0, 3],
		[0, 2, 2],
		[1, 1, 2],
		[1, 2, 3],
	] as const;
	const transitions = [[0, 1, options.transitionWeight ?? 3]] as const;
	const encoder = new TextEncoder();
	const attributeBytes = attributes.map((attribute) => encoder.encode(attribute));
	const size = 20 + attributeBytes.reduce((sum, value) => sum + 4 + value.byteLength, 0) + states.length * 16 + transitions.length * 12;
	const buffer = new ArrayBuffer(size);
	const view = new DataView(buffer);
	let offset = 0;
	for (const byte of encoder.encode('VCRF')) view.setUint8(offset++, byte);
	view.setUint16(offset, 1, true);
	offset += 2;
	view.setUint16(offset, 3, true);
	offset += 2;
	view.setUint32(offset, attributes.length, true);
	offset += 4;
	view.setUint32(offset, states.length, true);
	offset += 4;
	view.setUint32(offset, transitions.length, true);
	offset += 4;
	for (const value of attributeBytes) {
		view.setUint32(offset, value.byteLength, true);
		offset += 4;
		new Uint8Array(buffer, offset, value.byteLength).set(value);
		offset += value.byteLength;
	}
	for (const [attributeIndex, labelIndex, weight] of states) {
		view.setUint32(offset, attributeIndex, true);
		view.setUint8(offset + 4, labelIndex);
		view.setUint8(offset + 5, options.padding ?? 0);
		view.setFloat64(offset + 8, weight, true);
		offset += 16;
	}
	for (const [from, to, weight] of transitions) {
		view.setUint8(offset, from);
		view.setUint8(offset + 1, to);
		view.setFloat64(offset + 4, weight, true);
		offset += 12;
	}
	return buffer;
}

const labels = ['B-NDAY', 'I-NDAY', 'O'] as const;

test('decodes exact Float64 weights and finds the global Viterbi optimum', () => {
	const model = decodePortableCrfModel(encodeModel(), labels);
	assert.deepEqual(model.stateFeatures, [
		['wi:11', 0, 3],
		['wi:11', 2, 2],
		['wi:07', 1, 2],
		['wi:07', 2, 3],
	]);
	const tokens = tokenizeVietnameseText('11 07').paragraphs[0].tokens;
	assert.deepEqual(createCrfDetector(model).detect(tokens), ['B-NDAY', 'I-NDAY']);
});

test('rejects malformed binaries and non-finite weights', () => {
	const badMagic = encodeModel();
	new Uint8Array(badMagic)[0] = 0;
	assert.throws(() => decodePortableCrfModel(badMagic, labels), /magic/);
	assert.throws(() => decodePortableCrfModel(encodeModel().slice(0, 30), labels), /truncated/);
	assert.throws(() => decodePortableCrfModel(encodeModel({ padding: 1 }), labels), /padding/);
	assert.throws(() => decodePortableCrfModel(encodeModel({ transitionWeight: Number.NaN }), labels), /finite/);
});

test('uses lower label index for deterministic score ties', () => {
	const model = decodePortableCrfModel(encodeModel({ transitionWeight: 0 }), labels);
	const tokens = tokenizeVietnameseText('khác').paragraphs[0].tokens;
	assert.deepEqual(createCrfDetector(model).detect(tokens), ['B-NDAY']);
});

test('repairs invalid I labels and ignores the unsupported legacy state', () => {
	assert.deepEqual(reconstructDetectedSpans(['I-NDAY', 'O']), [{ type: 'NDAY', startToken: 0, endToken: 1 }]);
	assert.deepEqual(reconstructDetectedSpans(['B-USS', 'I-LWRD', 'O']), [{ type: 'LWRD', startToken: 1, endToken: 2 }]);
});

test('matches labels generated by the pinned Python checkpoint oracle', () => {
	const manifest = JSON.parse(readAsset('model-manifest.json').toString('utf8')) as { labels: CheckpointLabel[] };
	const model = decodePortableCrfModel(exactArrayBuffer(readAsset('crf-model.bin')), manifest.labels);
	const abbreviations = new Set(
		readAsset('abbreviations.txt')
			.toString('utf8')
			.split('\n')
			.map((line) => line.split(':', 1)[0])
			.filter(Boolean),
	);
	const detector = createCrfDetector(model, {
		vietnameseSyllables: new Set(readAsset('vietnamese-syllables.txt').toString('utf8').split('\n').filter(Boolean)),
		abbreviations,
		moneyUnits: new Set(['$', '€', '¥', '₫', 'đ', '฿', '₭', '₹', '₽', '₱', '£', '₩']),
		measurementUnits: new Set(['%', 'km', 'm']),
	});
	const goldens = JSON.parse(
		readFileSync(new URL('../fixtures/vietnamese-normalizer/reference-goldens.json', import.meta.url), 'utf8'),
	) as Array<{ tokens: string[]; labels: CheckpointLabel[] }>;
	for (const golden of goldens) {
		const tokens: SourceToken[] = golden.tokens.map((text) => ({
			text,
			original: text,
			leading: '',
			start: 0,
			end: text.length,
			kind: 'word',
		}));
		assert.deepEqual(detector.detect(tokens), golden.labels, golden.tokens.join(' '));
	}
});
